webcomposer_config.announcements_configuration:
  type: config_object
  label: 'Announcements Custom Configurations'
  mapping:
    title:
      type: label
      label: 'Announcements Lightbox Title'
    default_message:
      type: label
      label: 'Announcements Lightbox Default Message'
    see_all:
      type: label
      label: 'Announcements See all text'
    dismiss_all:
      type: label
      label: 'Announcements Dismiss all text'
