arcade_config.admin_settings:
  title: 'Arcade Configuration'
  description: 'Provides configuration for Nextbet Arcade'
  parent: system.admin_config
  route_name: arcade_config.admin_settings

arcade_config.game.categories:
  title: 'Manage Game Categories'
  parent: arcade_config.admin_settings
  description: 'Manage Game Categories'
  route_name: arcade_config.game.categories

arcade_config.game.thumbnails:
  title: 'Manage Game Thumbnails'
  parent: arcade_config.admin_settings
  description: 'Manage Game Thumbnails'
  route_name: arcade_config.game.thumbnails
