arcade_config.admin_settings:
  path: 'admin/config/arcade'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Arcade Configurations'
  requirements:
    _permission: 'administer nextbet arcade config'

arcade_config.game.categories:
  path: 'admin/config/arcade/categories/sorting'
  defaults:
    _controller: '\Drupal\arcade_config\Controller\DefaultController::placeholder'
    _title: 'Manage Game Categories'
  requirements:
    _permission: 'administer site configuration'

arcade_config.game.thumbnails:
  path: 'admin/config/arcade/games/sorting'
  defaults:
    _controller: '\Drupal\arcade_config\Controller\DefaultController::placeholder'
    _title: 'Manage Game Thumbnails'
  requirements:
    _permission: 'administer site configuration'
