virtual_config.admin_settings:
  path: 'admin/config/virtual'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Virtual Configuration'
  requirements:
    _permission: 'administer site configuration'

virtual_config.virtual_config_form:
  path: 'admin/config/virtual/virtualconfig'
  defaults:
    _form: 'Drupal\virtual_config\Form\VirtualConfigForm'
    _title: 'Virtual Configuration'
  requirements:
    _permission: 'administer site configuration'
