casino_games.games_configuration:
  type: config_object
  label: 'Games Custom Configurations'
  mapping:
    play_text:
      type: label
      label: 'Play Button Text'
    play_for_fun_text:
      type: label
      label: 'Play For Fun Link Text'
    game_info_text:
      type: label
      label: 'Game Info Link Text'
    game_real_play_text:
      type: label
      label: 'Real Play Button Text'
    filter_icon:
      type: label
      label: 'Game Filter Icon Text'
    filter_header:
      type: label
      label: 'Filter Lightbox Header Text'
    filter_submit:
      type: label
      label: 'Filter Lightbox Submit Botton Text'
    filter_clear:
      type: label
      label: 'Filter Lightbox Header Text'
    kebab_menu_text:
      type: label
      label: 'Category Kebab Menu Text'
    load_more_text:
      type: label
      label: 'Load More Text'
    favorites_text:
      type: label
      label: 'Favorites Tab Text'
    recently_played_text:
      type: label
      label: 'Recently Played Text'
    freeplay_lightbox_title:
      type: label
      label: 'Free Play Lightbox Title'
    freeplay_lightbox_content:
      type: text_format
      label: 'Free Play Lightbox Content'
      translatable: true
    html5_lightbox_title:
      type: label
      label: 'HTML5 Lightbox Title'
    html5_lightbox_content:
      type: text_format
      label: 'HTML5 Lightbox Content'
      translatable: true
    pas_error_lightbox_title:
      type: label
      label: 'PAS Error Lightbox Title'
    pas_error_lightbox_content:
      type: text_format
      label: 'PAS Error Lightbox Content'
      translatable: true
    drawer_switch:
      type: label
      label: 'Drawer switch'
      translatable: true
